"""Добавил таблицу заметок

Revision ID: 507a598a3f84
Revises: 6e241ecb4e82
Create Date: 2023-12-06 13:02:51.340800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507a598a3f84'
down_revision = '6e241ecb4e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id_note', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('note_name', sa.String(length=256), nullable=True),
    sa.Column('note_body', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_note')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
